repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, bigquery]
      - id: sqlfluff-fix
        args: [--dialect, bigquery]
